

let x = 5;
let y = 4;

console.log(typeof(x*y))
console.log(x%y)
console.log(x - y)
console.log(x+y)

// /* Increment dan Decrement */

let postfix = 5;
console.log(postfix++)

console.log(postfix)


let prefix = 5;
console.log(++prefix)

const bigNumber = 1234567890123456789012345678901234567890n;
const myInt = 1234567890123456789012345678901234567890;

console.log(typeof(bigNumber))
console.log(typeof(myInt))


const bigIntButSmall = 7n;
console.log(bigIntButSmall)
 string


const question = '"apa firts impression kamu tentang javascript"'
console.log(question)

let greet = "Hello";
let moreGreet = greet + greet;
console.log(moreGreet)

const myName = "Luke";
console.log(`Hello, my name is ${myName}.`);


// menggunakan backticks (`),
const nama = "yusuf";
console.log(`nama saya ${nama}. `)


// // boolean

const a = 10;
const b = 12;

let isGreater = a > b;
let isLess = a < b;

console.log(isGreater);
console.log(isLess);

